#!/usr/bin/env python3
"""Regenerate the embedded telemetry helpers inside the `khub` script from their
canonical sources in lib/telemetry/*.py.

The single-file install ships only `khub` (no lib/ beside it), so the same Python
sources are embedded in the script and materialised on demand — see tel_helper().
lib/telemetry/*.py stays the SOURCE OF TRUTH (the tests run against it); run this
after editing any of them. CI runs it and fails if the result isn't committed
(scripts/check-embedded-telemetry.sh), so the embedded copy can never drift.

    python3 scripts/embed-telemetry.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KHUB = os.path.join(ROOT, "khub")
HELPERS = [
    ("settings_merge.py", "_khub_py_settings_merge"),
    ("capture_hook.py", "_khub_py_capture_hook"),
    ("aggregate_tasks.py", "_khub_py_aggregate_tasks"),
]
BEGIN = "# >>> BEGIN embedded telemetry helpers (generated by scripts/embed-telemetry.py) >>>"
END = "# <<< END embedded telemetry helpers <<<"
DELIM = "KHUB_EMBEDDED_PY_EOF"


def build_block():
    out = [
        BEGIN,
        "# DO NOT EDIT BY HAND — regenerate with: python3 scripts/embed-telemetry.py",
        "# Source of truth: lib/telemetry/*.py",
    ]
    for fname, func in HELPERS:
        src = open(os.path.join(ROOT, "lib", "telemetry", fname), encoding="utf-8").read()
        if DELIM in src:
            sys.exit("error: heredoc delimiter %r appears in %s" % (DELIM, fname))
        out.append("%s() {" % func)
        out.append("cat <<'%s'" % DELIM)
        out.append(src.rstrip("\n"))
        out.append(DELIM)
        out.append("}")
    out.append(END)
    return "\n".join(out)


def main():
    text = open(KHUB, encoding="utf-8").read()
    try:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
    except ValueError:
        sys.exit("error: embed markers not found in khub — add the BEGIN/END block")
    new_text = text[:start] + build_block() + text[end:]
    if new_text != text:
        with open(KHUB, "w", encoding="utf-8") as fh:
            fh.write(new_text)
        print("embedded %d helpers into khub" % len(HELPERS))
    else:
        print("khub embedded helpers already up to date")


if __name__ == "__main__":
    main()
